name: MSBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  packages: write

env:
  VCPKG_COMMIT: 877e3dc2323a4d4c3c75e7168c22a0c4e921d4db
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [x86, x64]
        include:
          - platform: x86
            triplet: x86-windows
          - platform: x64
            triplet: x64-windows
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Restore from cache and install vcpkg
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: ${{ env.VCPKG_COMMIT }}
        appendedCacheKey: ${{ matrix.triplet }}
    - name: 'Setup NuGet/Vcpkg Credentials'
      shell: 'bash'
      run: >
        `./vcpkg/vcpkg fetch nuget | tail -n 1` \
          sources add \
          -source "https://nuget.pkg.github.com/rioki/index.json" \
          -storepasswordincleartext \
          -name "GitHub" \
          -username "rioki" \
          -password "${{ secrets.GITHUB_TOKEN }}"
        `./vcpkg/vcpkg fetch nuget | tail -n 1` \
          setapikey "${{ secrets.GITHUB_TOKEN }}" \
          -source "https://nuget.pkg.github.com/rioki/index.json"
    - name: Integrate vcpkg in MSBuild
      shell: 'bash'
      run: vcpkg.exe integrate install
    - name: Build (Debug)
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Debug /property:Platform=${{matrix.platform}} spdr.sln
    - name: Test (Debug)
      continue-on-error: true
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ${{matrix.platform}}/Debug/spdr-test.exe
    - name: Build (Release)
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Release /property:Platform=${{matrix.platform}} spdr.sln
    - name: Test (Release)
      continue-on-error: true
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ${{matrix.platform}}/Release/spdr-test.exe
